[build]
  nixpkgs = [
    "nodejs_18",
    "chromium",
    "libnss3",
    "libatk1.0",
    "libatk-bridge2",
    "libcups",
    "libgbm",
    "libasound2",
    "libpangocairo",
    "libxss",
    "libgtk-3",
    "libxshmfence",
    "libglu"
  ]
