[build]
nixpkgs = [
  "nodejs_18",
  "chromium",
  "nss",
  "atk",
  "atk-bridge",
  "cups",
  "libgbm",
  "alsa-lib",
  "pango",
  "gtk3",
  "mesa",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXScrnSaver",
  "xorg.libxcb",
  "xorg.libxshmfence",
  "glu"
]

[phases.build]
cmds = ["npm install"]
